name: Build Application Artefacts
on:
  push:
    branches: [master]
    paths:
      - '.github/**'
      - 'build.clj'
      - 'deps.edn'
      - 'infra/**'
      - 'resources/**'
      - 'src/**'

jobs:
  deployment:
    name: Build Server Artifact
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest

      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: clojure-${{ hashFiles('deps.edn') }}

      - run: clojure -T:build uber

      - uses: actions/cache/save@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: clojure-${{ hashFiles('deps.edn') }}

      - uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          strip_components: 1 # removes '/target' segment from the source path.
          source: 'target/learning-app.jar'
          target: '/opt/learning-app/'
          overwrite: true
          rename: learning-app.jar.tmp

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            set -euo pipefail
            mv -f /opt/learning-app/learning-app.jar.tmp /opt/learning-app/learning-app.jar
